INSERT INTO players (name) VALUES ( 'Roger Federer' );
INSERT INTO players (name) VALUES ( 'Rafael Nadal' );
INSERT INTO players (name) VALUES ( 'Novak Djokovic' );
INSERT INTO players (name) VALUES ( 'Andy Murray' );
INSERT INTO players (name) VALUES ( 'Serena Williams' );
INSERT INTO players (name) VALUES ( 'Naomi Osaka' );
INSERT INTO players (name) VALUES ( 'Ashleigh Barty' );
INSERT INTO players (name) VALUES ( 'Simona Halep' );
INSERT INTO players (name) VALUES ( 'Daniil Medvedev' );
INSERT INTO players (name) VALUES ( 'Stefanos Tsitsipas' );
INSERT INTO players (name) VALUES ( 'Dominic Thiem' );
INSERT INTO players (name) VALUES ( 'Alexander Zverev' );
INSERT INTO players (name) VALUES ( 'Bianca Andreescu' );
INSERT INTO players (name) VALUES ( 'Petra Kvitova' );
INSERT INTO players (name) VALUES ( 'Garbine Muguruza' );
INSERT INTO players (name) VALUES ( 'Karolina Pliskova' );
INSERT INTO players (name) VALUES ( 'Juan Martin del Potro' );
INSERT INTO players (name) VALUES ( 'Stan Wawrinka' );
INSERT INTO players (name) VALUES ( 'Angelique Kerber' );
INSERT INTO players (name) VALUES ( 'Elina Svitolina' );

INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (1, 2, 1);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (3, 4, 3);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (5, 6, 5);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (7, 8, 7);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (9, 10, 9);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (11, 12, 11);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (13, 14, 14);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (15, 16, 15);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (17, 18, 18);
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES (19, 20, 20);