INSERT INTO players (name) VALUES ( 'Moiseev Nikita' );
INSERT INTO players (name) VALUES ( 'Bataev Vladislav' );
INSERT INTO players (name) VALUES ( 'Lykin Maksim' );
INSERT INTO players (name) VALUES ( 'Kulgin Vladislav' );
INSERT INTO players (name) VALUES ( 'Semisotnov Roman' );
INSERT INTO players (name) VALUES ( 'Mizonov Stanislav' );
INSERT INTO players (name) VALUES ( 'Khrystyk Mark' );
INSERT INTO players (name) VALUES ( 'Papshev Alex' );
INSERT INTO players (name) VALUES ( 'Krivov Ilya' );
INSERT INTO players (name) VALUES ( 'Kolodin Nikita' );

INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 1, 2, 1 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 2, 3, 3 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 4, 3, 3 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 5, 6, 5 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 7, 3, 3 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 9, 7, 7 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 1, 9, 1 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 10, 4, 4 );
INSERT INTO matches (first_player_id, second_player_id, winner_player_id) VALUES ( 8, 2, 2 );